Showing a crash in GifClass.h
Adding a single serial.print moves the crash to this one, which seems to
imply a crash in the gif library?

GIF video start at 0 x 0 for size 96 x 64
1
2
4
5
6
1
Read sep: [⸮].

2
ERROR: gd_get_frame() failed!
GIF video end
duration: 100, remain: 88 (88.00%)
1073451780
1073422440
GIF video start at 0 x 0 for size 96 x 64
1
Read sep: [?].

2
ERROR: gd_get_frame() failed!
GIF video end
duration: 0, remain: 0 (nan%)
CORRUPT HEAP: Bad head at 0x3ffc1ddc. Expected 0xabba1234 got 0x3ffdfff8
assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/multi_heap_poisoning.c", line 214, function: multi_heap_free
abort() was called at PC 0x400de09b on core 1

Backtrace: 0x4008b9dc:0x3ffb1e70 0x4008bc09:0x3ffb1e90 0x400de09b:0x3ffb1eb0 0x4008b66d:0x3ffb1ee0 0x40084a16:0x3ffb1f00 0x40085de5:0x3ffb1f20 0x4000bec7:0x3ffb1f40 0x400d1cae:0x3ffb1f60 0x400dbd15:0x3ffb1fb0 0x4008a529:0x3ffb1fd0

Rebooting...

Crash in
    void gd_close_gif(gd_GIF *gif)
    {
        gif->fd->close();
----->  free(gif->table);
        free(gif);
    }